In [0]:
import numpy as np
import pandas as pd

In [0]:
dataframe = pd.read_csv('Churn_Modelling.csv')
#data = dataframe.values

In [0]:
x= dataframe.iloc[:,3:13].values
y = dataframe.iloc[:,13].values

In [7]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from keras.models import Sequential,Model
from keras.layers import Dense,Input,Activation

Using TensorFlow backend.


In [0]:
encoder = LabelEncoder()
#encoder.fit(x[:,2])
x[:,1] = encoder.fit_transform(x[:,1])
x[:,2] = encoder.fit_transform(x[:,2])

oneEncoder = OneHotEncoder(categorical_features = [1])
x = oneEncoder.fit_transform(x).toarray()
x = x[:,1:]

In [10]:
x

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [0]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


In [15]:

classifier = Sequential()
classifier.add(Dense(output_dim=6, input_dim = 11, init= 'uniform', activation = 'relu'))
classifier.add(Dense(1, activation = 'sigmoid'))
classifier.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
classifier.fit(x_train,y_train,batch_size = 10,nb_epoch = 40)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=11, activation="relu", units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/keras/models.py:981: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/40
8000/8000 [==============================] - 1s 180us/step - loss: 0.4896 - acc: 0.8099
Epoch 2/40
8000/8000 [==============================] - 1s 134us/step - loss: 0.3966 - acc: 0.8337
Epoch 3/40
8000/8000 [==============================] - 1s 126us/step - loss: 0.3714 - acc: 0.8479
Epoch 4/40
8000/8000 [==============================] - 1s 125us/step - loss: 0.3588 - acc: 0.8544
Epoch 5/40
8000/8000 [==============================] - 1s 124us/step - loss: 0.3519 - acc: 0.8577
Epoch 6/40
8000/8000 [==============================] - 1s 125us/step - loss: 0.3485 - acc: 0.8597
Epoch 7/40
8000/8000 [==============================] - 1s 123us/step - loss: 0.3462 - acc: 0.8585
Epoch 8/40
8000/8000 [==============================] - 1s 125us/step - loss: 0.3450 - acc: 0.8592
Epoch 9/40
8000/8000 [==============================] - 1s 124us/step - loss: 0.3439 - acc: 0.8587
Epoch 10/40
8000/8000 [==============================] - 1s 125us/step - loss: 0.3426 - acc: 0.8627
Epoch 11/

In [16]:
classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 6)                 72        
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 7         
Total params: 79
Trainable params: 79
Non-trainable params: 0
_________________________________________________________________


In [17]:
classifier.input_layers

In [0]:
y_pred = classifier.predict(x_test)
#y_pred= (y_pred > 0.5)

In [21]:
y_pred

array([[0.03300302],
       [0.02176017],
       [0.13681385],
       ...,
       [0.7050545 ],
       [0.15456761],
       [0.29692483]], dtype=float32)

In [0]:
pred_ = classifier.predict(sc.transform(np.array([[0.0,0,6000,1,40,3,60000,2,1,1,50000]])))

In [27]:
pred_

array([[0.7977505]], dtype=float32)