In [2]:
import numpy as np


In [5]:
a=np.array([1,2,3])

In [6]:
b=np.array([4,5,6])

In [9]:
c=a+b

In [10]:
c

array([5, 7, 9])

In [11]:
c=a-b

In [12]:
c

array([-3, -3, -3])

In [18]:
np.multiply (a,b)

array([ 4, 10, 18])

In [19]:
c=a/b

In [20]:
c

array([0.25, 0.4 , 0.5 ])