In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('Human_Resources_Employee_Attrition.csv')
df.head()

satisfaction_level  last_evaluation  number_of_projects  \
0                0.38             0.53                   2   
1                0.80             0.86                   5   
2                0.11             0.88                   7   
3                0.72             0.87                   5   
4                0.37             0.52                   2   

   average_monthly_hours  years_at_company  work_accident  left  \
0                    157                 3              0     1   
1                    262                 6              0     1   
2                    272                 4              0     1   
3                    223                 5              0     1   
4                    159                 3              0     1   

   promotion_last_5years department  salary  
0                      0      sales     low  
1                      0      sales  medium  
2                      0      sales  medium  
3                      0      sales     low  
4                      0      sales     low

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
satisfaction_level       14999 non-null float64
last_evaluation          14999 non-null float64
number_of_projects       14999 non-null int64
average_monthly_hours    14999 non-null int64
years_at_company         14999 non-null int64
work_accident            14999 non-null int64
left                     14999 non-null int64
promotion_last_5years    14999 non-null int64
department               14999 non-null object
salary                   14999 non-null object
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [4]:
df.head(20)

satisfaction_level  last_evaluation  number_of_projects  \
0                 0.38             0.53                   2   
1                 0.80             0.86                   5   
2                 0.11             0.88                   7   
3                 0.72             0.87                   5   
4                 0.37             0.52                   2   
5                 0.41             0.50                   2   
6                 0.10             0.77                   6   
7                 0.92             0.85                   5   
8                 0.89             1.00                   5   
9                 0.42             0.53                   2   
10                0.45             0.54                   2   
11                0.11             0.81                   6   
12                0.84             0.92                   4   
13                0.41             0.55                   2   
14                0.36             0.56                   2   
15                0.38             0.54                   2   
16                0.45             0.47                   2   
17                0.78             0.99                   4   
18                0.45             0.51                   2   
19                0.76             0.89                   5   

    average_monthly_hours  years_at_company  work_accident  left  \
0                     157                 3              0     1   
1                     262                 6              0     1   
2                     272                 4              0     1   
3                     223                 5              0     1   
4                     159                 3              0     1   
5                     153                 3              0     1   
6                     247                 4              0     1   
7                     259                 5              0     1   
8                     224                 5              0     1   
9                     142                 3              0     1   
10                    135                 3              0     1   
11                    305                 4              0     1   
12                    234                 5              0     1   
13                    148                 3              0     1   
14                    137                 3              0     1   
15                    143                 3              0     1   
16                    160                 3              0     1   
17                    255                 6              0     1   
18                    160                 3              1     1   
19                    262                 5              0     1   

    promotion_last_5years department  salary  
0                       0      sales     low  
1                       0      sales  medium  
2                       0      sales  medium  
3                       0      sales     low  
4                       0      sales     low  
5                       0      sales     low  
6                       0      sales     low  
7                       0      sales     low  
8                       0      sales     low  
9                       0      sales     low  
10                      0      sales     low  
11                      0      sales     low  
12                      0      sales     low  
13                      0      sales     low  
14                      0      sales     low  
15                      0      sales     low  
16                      0      sales     low  
17                      0      sales     low  
18                      1      sales     low  
19                      0      sales     low

In [5]:
X=df.drop(['department'],axis=1)

In [6]:
X

satisfaction_level  last_evaluation  number_of_projects  \
0                    0.38             0.53                   2   
1                    0.80             0.86                   5   
2                    0.11             0.88                   7   
3                    0.72             0.87                   5   
4                    0.37             0.52                   2   
5                    0.41             0.50                   2   
6                    0.10             0.77                   6   
7                    0.92             0.85                   5   
8                    0.89             1.00                   5   
9                    0.42             0.53                   2   
10                   0.45             0.54                   2   
11                   0.11             0.81                   6   
12                   0.84             0.92                   4   
13                   0.41             0.55                   2   
14                   0.36             0.56                   2   
15                   0.38             0.54                   2   
16                   0.45             0.47                   2   
17                   0.78             0.99                   4   
18                   0.45             0.51                   2   
19                   0.76             0.89                   5   
20                   0.11             0.83                   6   
21                   0.38             0.55                   2   
22                   0.09             0.95                   6   
23                   0.46             0.57                   2   
24                   0.40             0.53                   2   
25                   0.89             0.92                   5   
26                   0.82             0.87                   4   
27                   0.40             0.49                   2   
28                   0.41             0.46                   2   
29                   0.38             0.50                   2   
...                   ...              ...                 ...   
14969                0.43             0.46                   2   
14970                0.78             0.93                   4   
14971                0.39             0.45                   2   
14972                0.11             0.97                   6   
14973                0.36             0.52                   2   
14974                0.36             0.54                   2   
14975                0.10             0.79                   7   
14976                0.40             0.47                   2   
14977                0.81             0.85                   4   
14978                0.40             0.47                   2   
14979                0.09             0.93                   6   
14980                0.76             0.89                   5   
14981                0.73             0.93                   5   
14982                0.38             0.49                   2   
14983                0.72             0.84                   5   
14984                0.40             0.56                   2   
14985                0.91             0.99                   5   
14986                0.85             0.85                   4   
14987                0.90             0.70                   5   
14988                0.46             0.55                   2   
14989                0.43             0.57                   2   
14990                0.89             0.88                   5   
14991                0.09             0.81                   6   
14992                0.40             0.48                   2   
14993                0.76             0.83                   6   
14994                0.40             0.57                   2   
14995                0.37             0.48                   2   
14996                0.37             0.53                   2   
14997                0.11             0.96     

In [7]:
X.head(20)

satisfaction_level  last_evaluation  number_of_projects  \
0                 0.38             0.53                   2   
1                 0.80             0.86                   5   
2                 0.11             0.88                   7   
3                 0.72             0.87                   5   
4                 0.37             0.52                   2   
5                 0.41             0.50                   2   
6                 0.10             0.77                   6   
7                 0.92             0.85                   5   
8                 0.89             1.00                   5   
9                 0.42             0.53                   2   
10                0.45             0.54                   2   
11                0.11             0.81                   6   
12                0.84             0.92                   4   
13                0.41             0.55                   2   
14                0.36             0.56                   2   
15                0.38             0.54                   2   
16                0.45             0.47                   2   
17                0.78             0.99                   4   
18                0.45             0.51                   2   
19                0.76             0.89                   5   

    average_monthly_hours  years_at_company  work_accident  left  \
0                     157                 3              0     1   
1                     262                 6              0     1   
2                     272                 4              0     1   
3                     223                 5              0     1   
4                     159                 3              0     1   
5                     153                 3              0     1   
6                     247                 4              0     1   
7                     259                 5              0     1   
8                     224                 5              0     1   
9                     142                 3              0     1   
10                    135                 3              0     1   
11                    305                 4              0     1   
12                    234                 5              0     1   
13                    148                 3              0     1   
14                    137                 3              0     1   
15                    143                 3              0     1   
16                    160                 3              0     1   
17                    255                 6              0     1   
18                    160                 3              1     1   
19                    262                 5              0     1   

    promotion_last_5years  salary  
0                       0     low  
1                       0  medium  
2                       0  medium  
3                       0     low  
4                       0     low  
5                       0     low  
6                       0     low  
7                       0     low  
8                       0     low  
9                       0     low  
10                      0     low  
11                      0     low  
12                      0     low  
13                      0     low  
14                      0     low  
15                      0     low  
16                      0     low  
17                      0     low  
18                      1     low  
19                      0     low

In [8]:
x = X.iloc[:,0:-1].values
y = X.iloc[:,-1].values

In [9]:
x,y

(array([[0.38, 0.53, 2.  , ..., 0.  , 1.  , 0.  ],
        [0.8 , 0.86, 5.  , ..., 0.  , 1.  , 0.  ],
        [0.11, 0.88, 7.  , ..., 0.  , 1.  , 0.  ],
        ...,
        [0.37, 0.53, 2.  , ..., 0.  , 1.  , 0.  ],
        [0.11, 0.96, 6.  , ..., 0.  , 1.  , 0.  ],
        [0.37, 0.52, 2.  , ..., 0.  , 1.  , 0.  ]]),
 array(['low', 'medium', 'medium', ..., 'low', 'low', 'low'], dtype=object))

In [10]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder=LabelEncoder()
x[:,7]=labelencoder.fit_transform(x[:,7])
encoder=OneHotEncoder(categorical_features=[7])
x=encoder.fit_transform(x).toarray()


In [11]:
x

array([[1.  , 0.  , 0.38, ..., 3.  , 0.  , 1.  ],
       [1.  , 0.  , 0.8 , ..., 6.  , 0.  , 1.  ],
       [1.  , 0.  , 0.11, ..., 4.  , 0.  , 1.  ],
       ...,
       [1.  , 0.  , 0.37, ..., 3.  , 0.  , 1.  ],
       [1.  , 0.  , 0.11, ..., 4.  , 0.  , 1.  ],
       [1.  , 0.  , 0.37, ..., 3.  , 0.  , 1.  ]])

In [12]:
x=pd.DataFrame(x)

In [25]:
x.head()

0    1     2     3    4      5    6    7    8
0  1.0  0.0  0.38  0.53  2.0  157.0  3.0  0.0  1.0
1  1.0  0.0  0.80  0.86  5.0  262.0  6.0  0.0  1.0
2  1.0  0.0  0.11  0.88  7.0  272.0  4.0  0.0  1.0
3  1.0  0.0  0.72  0.87  5.0  223.0  5.0  0.0  1.0
4  1.0  0.0  0.37  0.52  2.0  159.0  3.0  0.0  1.0

In [14]:
x.head(20)

0    1     2     3    4      5    6    7    8
0   1.0  0.0  0.38  0.53  2.0  157.0  3.0  0.0  1.0
1   1.0  0.0  0.80  0.86  5.0  262.0  6.0  0.0  1.0
2   1.0  0.0  0.11  0.88  7.0  272.0  4.0  0.0  1.0
3   1.0  0.0  0.72  0.87  5.0  223.0  5.0  0.0  1.0
4   1.0  0.0  0.37  0.52  2.0  159.0  3.0  0.0  1.0
5   1.0  0.0  0.41  0.50  2.0  153.0  3.0  0.0  1.0
6   1.0  0.0  0.10  0.77  6.0  247.0  4.0  0.0  1.0
7   1.0  0.0  0.92  0.85  5.0  259.0  5.0  0.0  1.0
8   1.0  0.0  0.89  1.00  5.0  224.0  5.0  0.0  1.0
9   1.0  0.0  0.42  0.53  2.0  142.0  3.0  0.0  1.0
10  1.0  0.0  0.45  0.54  2.0  135.0  3.0  0.0  1.0
11  1.0  0.0  0.11  0.81  6.0  305.0  4.0  0.0  1.0
12  1.0  0.0  0.84  0.92  4.0  234.0  5.0  0.0  1.0
13  1.0  0.0  0.41  0.55  2.0  148.0  3.0  0.0  1.0
14  1.0  0.0  0.36  0.56  2.0  137.0  3.0  0.0  1.0
15  1.0  0.0  0.38  0.54  2.0  143.0  3.0  0.0  1.0
16  1.0  0.0  0.45  0.47  2.0  160.0  3.0  0.0  1.0
17  1.0  0.0  0.78  0.99  4.0  255.0  6.0  0.0  1.0
18  0.0  1.0  0.45  0.51  2.0  160.0  3.0  1.0  1.0
19  1.0  0.0  0.76  0.89  5.0  262.0  5.0  0.0  1.0

In [15]:
x.corr()

0         1         2         3         4         5         6  \
0  1.000000 -1.000000 -0.025605  0.008684  0.006064  0.003544 -0.067433   
1 -1.000000  1.000000  0.025605 -0.008684 -0.006064 -0.003544  0.067433   
2 -0.025605  0.025605  1.000000  0.105021 -0.142970 -0.020048 -0.100866   
3  0.008684 -0.008684  0.105021  1.000000  0.349333  0.339742  0.131591   
4  0.006064 -0.006064 -0.142970  0.349333  1.000000  0.417211  0.196786   
5  0.003544 -0.003544 -0.020048  0.339742  0.417211  1.000000  0.127755   
6 -0.067433  0.067433 -0.100866  0.131591  0.196786  0.127755  1.000000   
7 -0.039245  0.039245  0.058697 -0.007104 -0.004741 -0.010143  0.002120   
8  0.061788 -0.061788 -0.388375  0.006567  0.023787  0.071287  0.144822   

          7         8  
0 -0.039245  0.061788  
1  0.039245 -0.061788  
2  0.058697 -0.388375  
3 -0.007104  0.006567  
4 -0.004741  0.023787  
5 -0.010143  0.071287  
6  0.002120  0.144822  
7  1.000000 -0.154622  
8 -0.154622  1.000000

In [16]:
from sklearn.preprocessing import StandardScaler
Stand=StandardScaler()
s=Stand.fit_transform(x)

In [17]:
s

array([[ 0.14741182, -0.14741182, -0.93649469, ..., -0.34123516,
        -0.41116529,  1.788917  ],
       [ 0.14741182, -0.14741182,  0.75281433, ...,  1.71343614,
        -0.41116529,  1.788917  ],
       [ 0.14741182, -0.14741182, -2.02247906, ...,  0.34365527,
        -0.41116529,  1.788917  ],
       ...,
       [ 0.14741182, -0.14741182, -0.97671633, ..., -0.34123516,
        -0.41116529,  1.788917  ],
       [ 0.14741182, -0.14741182, -2.02247906, ...,  0.34365527,
        -0.41116529,  1.788917  ],
       [ 0.14741182, -0.14741182, -0.97671633, ..., -0.34123516,
        -0.41116529,  1.788917  ]])

In [18]:
s.shape

(14999, 9)

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(s,y,test_size=0.2,random_state=0)
x_train

array([[ 0.14741182, -0.14741182,  0.55170611, ...,  1.02854571,
        -0.41116529,  1.788917  ],
       [ 0.14741182, -0.14741182, -1.94203577, ...,  1.02854571,
        -0.41116529, -0.55899743],
       [ 0.14741182, -0.14741182,  0.22993297, ..., -0.34123516,
        -0.41116529, -0.55899743],
       ...,
       [ 0.14741182, -0.14741182,  0.31037625, ..., -1.0261256 ,
        -0.41116529, -0.55899743],
       [ 0.14741182, -0.14741182,  0.67237104, ..., -0.34123516,
        -0.41116529, -0.55899743],
       [ 0.14741182, -0.14741182, -0.21250511, ..., -1.0261256 ,
        -0.41116529, -0.55899743]])

In [20]:
x_test

array([[ 0.14741182, -0.14741182, -0.69516483, ..., -0.34123516,
        -0.41116529,  1.788917  ],
       [ 0.14741182, -0.14741182, -0.25272675, ..., -0.34123516,
        -0.41116529, -0.55899743],
       [ 0.14741182, -0.14741182,  0.43104118, ..., -1.0261256 ,
        -0.41116529, -0.55899743],
       ...,
       [ 0.14741182, -0.14741182, -0.97671633, ..., -0.34123516,
        -0.41116529,  1.788917  ],
       [ 0.14741182, -0.14741182, -0.37339168, ..., -1.0261256 ,
        -0.41116529, -0.55899743],
       [ 0.14741182, -0.14741182, -1.94203577, ...,  0.34365527,
        -0.41116529, -0.55899743]])

In [21]:
x_test.shape

(3000, 9)

In [22]:
x_train.shape

(11999, 9)

In [26]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
log.fit(x_train,y_train)
predict=log.predict(x_test)
predict.mean()*100

TypeError: unsupported operand type(s) for /: 'str' and 'int'

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [ ]:
from sklearn.linear_model import LinearRegression
log=LinearRegression()
log.fit(x_train,y_train)
predict=log.predict(x_test)