In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [16]:
from sklearn.externals import joblib
data=joblib.load('iris.joblib.dat')

In [20]:
data

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=nan, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [21]:
x=iris.data
y=iris.target

In [22]:
x,y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [25]:
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2,random_state=42)

In [28]:
from sklearn import svm
from xgboost import XGBClassifier
clf = XGBClassifier()
clf

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [31]:
clf.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [34]:
y_pred = clf.predict(x_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [35]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [36]:
#classification accuracy
from sklearn import metrics
print(metrics.accuracy_score(y_test, y_pred))

1.0


In [38]:
#importing library and segregation of data as train and test using DMatrix Data structure
import xgboost as xgb

dtrain = xgb.DMatrix(x_train, label=y_train)
dtest = xgb.DMatrix(x_test, label=y_test)

In [39]:
dtrain,dtest

(<xgboost.core.DMatrix at 0x1ffb554a080>,
 <xgboost.core.DMatrix at 0x1ffb554a0f0>)

In [43]:
#paramaters 
param = {
    'max_depth': 3, 
    'eta': 0.3, 
    'silent': 1,
    'objective': 'multi:softprob',
    'num_class':3} 
num_round = 5


In [45]:
bst = xgb.train(param, dtrain, num_round)
            

In [46]:
bst

In [47]:
y_predict = bst.predict(dtest)

In [48]:
y_predict

array([[0.08698964, 0.82529145, 0.08771889],
       [0.8246389 , 0.08897055, 0.08639057],
       [0.08697931, 0.09218644, 0.8208342 ],
       [0.08499288, 0.8063477 , 0.10865935],
       [0.07517892, 0.7132403 , 0.21158072],
       [0.8246389 , 0.08897055, 0.08639057],
       [0.08698964, 0.82529145, 0.08771889],
       [0.08697931, 0.09218644, 0.8208342 ],
       [0.08289975, 0.7864897 , 0.1306105 ],
       [0.08698964, 0.82529145, 0.08771889],
       [0.08697931, 0.09218644, 0.8208342 ],
       [0.8246389 , 0.08897055, 0.08639057],
       [0.8246389 , 0.08897055, 0.08639057],
       [0.8246389 , 0.08897055, 0.08639057],
       [0.8246389 , 0.08897055, 0.08639057],
       [0.08499288, 0.8063477 , 0.10865935],
       [0.08697931, 0.09218644, 0.8208342 ],
       [0.08656566, 0.82126904, 0.09216528],
       [0.08698964, 0.82529145, 0.08771889],
       [0.08697931, 0.09218644, 0.8208342 ],
       [0.8246389 , 0.08897055, 0.08639057],
       [0.08366104, 0.12681969, 0.78951925],
       [0.

In [51]:
bst = xgb.train(param, dtrain,num_round)

In [52]:
y_predict=bst.predict(dtest)

In [54]:
bst.dump_model('dump.raw.')

In [55]:
['bst_model.pkl']

['bst_model.pkl']