# DataSetForEncoder

In [1]:
import pandas as pd
import numpy as np

In [9]:
df=pd.read_csv('DataSetForEncoder.csv')

In [11]:
df

Country   Age   Salary Purchase
0   France  44.0  72000.0       No
1    Spain  27.0  48000.0      Yes
2  Germany  30.0  54000.0       No
3    Spain  38.0  61000.0       No
4  Germany  40.0      NaN      Yes
5   France  35.0  58000.0      Yes
6    Spain   NaN  52000.0       No
7   France  48.0  79000.0      Yes
8  Germany  50.0  83000.0       No
9   France  37.0  67000.0      Yes

In [15]:
df.shape

(10, 4)

In [19]:
x=df.iloc[:,0:3].values
y=df.iloc[:,3].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [20]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [24]:
#import the imputer
from sklearn.preprocessing  import Imputer
imputer = Imputer(missing_values='NaN',axis=0,strategy='mean')
imputer = imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [26]:
x.shape

(10, 3)

In [40]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
label_x = LabelEncoder()
x[:,0] = label_x.fit_transform(x[:,0])
#print(x)
onehotencoder = OneHotEncoder(categorical_features= [0])

x = onehotencoder.fit_transform(x).toarray()
#print(x)
label_y = LabelEncoder()
y = label_y.fit_transform(y)
print(y)


[0 1 0 0 1 1 0 1 0 1]


In [43]:
x

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 4.40000000e+01, 7.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 2.70000000e+01, 4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 3.00000000e+01, 5.40000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 3.80000000e+01, 6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 4.00000000e+01, 6.37777778e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 3.50000000e+01, 5.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 3.87777778e+01, 5.

In [52]:
#splitting the dataset in to the training set and test set
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [56]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)
sc_y=StandardScaler()

x_test

array([[ 1.        , -1.        ,  1.        , -1.        ,  2.64575131,
        -0.77459667, -1.45882927, -0.90166297],
       [ 1.        , -1.        ,  1.        , -1.        ,  2.64575131,
        -0.77459667,  1.98496442,  2.13981082]])

In [57]:
x_train

array([[ 1.        , -1.        ,  1.        , -1.        ,  2.64575131,
        -0.77459667,  0.26306757,  0.12381479],
       [-1.        ,  1.        , -1.        ,  1.        , -0.37796447,
        -0.77459667, -0.25350148,  0.46175632],
       [ 1.        , -1.        ,  1.        , -1.        , -0.37796447,
         1.29099445, -1.97539832, -1.53093341],
       [ 1.        , -1.        ,  1.        , -1.        , -0.37796447,
         1.29099445,  0.05261351, -1.11141978],
       [-1.        ,  1.        , -1.        ,  1.        , -0.37796447,
        -0.77459667,  1.64058505,  1.7202972 ],
       [ 1.        , -1.        ,  1.        , -1.        , -0.37796447,
         1.29099445, -0.0813118 , -0.16751412],
       [-1.        ,  1.        , -1.        ,  1.        , -0.37796447,
        -0.77459667,  0.95182631,  0.98614835],
       [-1.        ,  1.        , -1.        ,  1.        , -0.37796447,
        -0.77459667, -0.59788085, -0.48214934]])